### ISSUE TITLE
Display Date on Homepage

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/WorkWise#17]
## Instructions
- Fetch Date using javascript and display it in the middle of the homepage. 
- Display the date below the time on homepage
- Make a new folder called `components` inside the `src` folder. Inside the `components` folder make a file called `date.js` and write the code for this component inside it.
- Call this component on the `Homepage.js` file. 
- If you need any help, you can ping me, Manas or Anurag on Discord.

**Comment by vishalola** [comment]
claim

**Comment by Manas2403** [comment]
Assigned to @vishalola .You have a time of two days to complete this issue. Please submit the PR before the deadline. If you need any help, you can reach out to us. Also, in case you submit a PR after the Background Image issue is closed, make sure that your code has no merge conflicts with this repo. Make sure to fetch upstream your forked repo before submitting a PR.

**Comment by vishalola** [comment]
@Manas2403 it is done
