### ISSUE TITLE
Change Website Head Title and Update Favicon

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#22]
## Instructions
- Change the website title to : "WorkWise"
- Change the favicon with the website logo. You can find the logo [here](https://www.figma.com/file/gtCWLq9mxxM3b8r9gkbxti/WorkWise-logo-(Copy)?node-id=0%3A1&t=8YAYCuJCN85OLf0f-1)
- Change the `content` attribute of `meta` data with the description of WorkWise

**Comment by frikinomad** [comment]
Claim

**Comment by ananyaa07** [comment]
claim

**Comment by anshgeez31** [comment]
claim

**Comment by ShrutiBilolikar** [comment]
claim

**Comment by atharva-gadekar** [comment]
@frikinomad You have time till 00:15 am on 23rd December to complete this issue.

**Comment by atharva-gadekar** [comment]
@frikinomad This is your 4th issue. It is a rule that one contributor can't have more than 3 issues in OpenCode at one time.
