### ISSUE TITLE
Fetch a Random Quote using any public API or using npm an package

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#23]
## Instructions 
- Example Quote: "Inspiration does exist, but it must find you working. - Pablo Picasso"
- Place the quote in the bottom centre of the screen. 
- Load a new quote every 5 minutes. Make sure that the transition between quotes is smooth for eg. : fade-in fade-out.
- Loading animations for quotes would be preferred.
- The exact design for the same will be posted soon in this thread.

You can ping us on Discord in the WorkWise channel if you need any help.

**Comment by Im-Madhur-Gupta** [comment]
claim

**Comment by atharva-gadekar** [comment]
Reference Designs : 

![image](https://user-images.githubusercontent.com/97454406/208756674-9c802ae9-dde6-4e77-aba9-fc0156ed3179.png)

![image](https://user-images.githubusercontent.com/97454406/208756723-582a2318-e847-4166-adbf-396f70460a2a.png)

**Comment by atharva-gadekar** [comment]
@Im-Madhur-Gupta Updates?

**Comment by Im-Madhur-Gupta** [comment]
@atharva-gadekar almost done, will be able to complete by tonight.

**Comment by some-earth11** [comment]
Is this issue resolved ? if not , I'm interested to volunteer 
@atharva-gadekar

**Comment by atharva-gadekar** [comment]
@some-earth11 This issue was resolved by @Im-Madhur-Gupta , please stay tuned, more issues are upcoming for you to contribute to!
