### ISSUE TITLE
Readme Changes

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#25]
## Instructions
- Fix the errors in the outermost Readme file of WorkWise.
- Add a contributors section and include an image of all the contributors in it. You can do this easily by using [this](https://contrib.rocks/preview?repo=angular%2Fangular-ja) link.
- You can make other content changes or styling changes as well which can improve the Readme
- You can ping me on [Discord](https://discord.gg/6p3J7bwv) if you need any help.

**Comment by pavanvnk** [comment]
Claim

**Comment by zitsav** [comment]
Claim

**Comment by atharva-gadekar** [comment]
@pavanvnk You have two days to complete this issue.

**Comment by atharva-gadekar** [comment]
@pavanvnk Updates?

**Comment by pavanvnk** [comment]
I will complete it by evening

**Comment by atharva-gadekar** [comment]
Good work @pavanvnk
