### ISSUE TITLE
Display the Weather Widget

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#29]
## Instructions
- Refer to the design below and implement the weather widget
- Display all the details of the weather widget like the icon, temperature, and climate as shown in the design.
- These details must be displayed using API. You can use [this](https://openweathermap.org/current) for completing this task or you may choose any other free API.
- Make sure that the API is either called upon reloading or after every hour.
 
You can always ping us on discord in the WorkWise channel to get any help. 

### The Design : 
![image](https://user-images.githubusercontent.com/97454406/209164684-b7f3ce06-2117-4b41-9563-3ab9f66292ce.png)

**Comment by GammaMicrowave** [comment]
claim

**Comment by ananyaa07** [comment]
claim

**Comment by ananyaa07** [comment]
claim

**Comment by atharva-gadekar** [comment]
@GammaMicrowave You have 2 days to complete this issue. Make sure that you include icons for all types of climates. Good Luck!

**Comment by antsharma** [comment]
claim

**Comment by atharva-gadekar** [comment]
Great Work @GammaMicrowave!
