### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JohnnyOhms** [opencodeiiita/WorkWise#31]
Please i want  join to the communty and contribute to this project

**Comment by JohnnyOhms** [comment]
approve pls

**Comment by atharva-gadekar** [comment]
Hello @JohnnyOhms , I will let you know soon

**Comment by JohnnyOhms** [comment]
ok, am always avaliable @atharva-gadekar

**Comment by atharva-gadekar** [comment]
Have you registered on Devfolio @JohnnyOhms ?

**Comment by JohnnyOhms** [comment]
not yet sir, how can i register @atharva-gadekar
