### ISSUE TITLE
Implement the Bookmarks Button

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#33]
### What do you need to know/learn
- This will be a difficult issue as compared to the previous ones and will require you to learn about three things 
  - Saving Data in the Local Storage
  - Animations in React
  - Importing and using Ant Design

### The Designs 
![image](https://user-images.githubusercontent.com/97454406/209325748-c5a98cb2-d3eb-4401-8ea1-0158061448c0.png)
![image](https://user-images.githubusercontent.com/97454406/209325895-f6efad88-f745-4dd3-9fad-0e6941a412f7.png)

Design Credits : @ananyaa07 

### The Task
- This will be a forty-pointer task. These are the steps you need to follow
  - Place the bookmark icon on the top left of the screen. You can import the icon from [here](https://www.figma.com/file/oSJGhiZsnyFtukferlag60/Untitled-(Copy)?node-id=0%3A1&t=X5l2Nyo6ailYlkQc-0)
  - On Clicking the bookmark icon, it would expand horizontally into a ribbon. This process must be animated.
  - The logo for each bookmark (element) must be fetched using this [API](https://favicongrabber.com/service-api-reference) or any equivalent API.
  - On clicking each bookmark, the user must be redirected to the URL for that particular bookmark.
  - There should be a `+` icon at the end of the bookmarks bar as shown in the Design.
  - Upon clicking this `+` icon, a modal window must be displayed. Use _**Ant Design**_ to display the modal window.
  - The modal window should only take the URL as input.
  - The element must be then added to the bookmarks bar and the favicon for that URL must be fetched using API. 
  - All the bookmarks must be stored in the local storage so that they are not lost upon reloading
  - On clicking the bookmarks button again, the ribbon should collapse. You must animate this as well.
  - You must document how you are storing data in the local storage. This will help others understand the code for later issues.
 
You can ignore the calendar icon for now, just place the bookmarks icon on the top left of the screen.

> You can Ping me or @Manas2403 or @BuddyLongLegs on Discord in the WorkWise Channel if you need any help. All the very best. You will have two days to complete this difficult task

**Comment by GammaMicrowave** [comment]
claim

**Comment by akshatsgh** [comment]
claim

**Comment by vishalola** [comment]
claim

**Comment by Kali-Decoder** [comment]
claim

**Comment by Aman1143** [comment]
claim

**Comment by JohnnyOhms** [comment]
claim

**Comment by Kali-Decoder** [comment]
Claim

**Comment by Kali-Decoder** [comment]
it has been 3 days .
is any one doing this issue

**Comment by atharva-gadekar** [comment]
@Kali-Decoder, @GammaMicrowave is working on this issue. He has already submitted a PR, and I have asked him to make certain changes to the same.

**Comment by atharva-gadekar** [comment]
Thankyou @GammaMicrowave. Great work!
