### ISSUE TITLE
Suggestions for Home Screen Widgets

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#35]
> These are the widgets issues that have been planned for the upcoming days. You can suggest more widgets (in addition to the ones given below) in this conversation which the user can enable or disable from the settings (which will be implemented soon).
- Calendar
- Settings
- Focus Timer

After the completion of all of these widgets, Stage 1 for WorkWise will be completed. We will then move into Stage 2 i.e the Kanban Board Page. We will then post issues for both pages together.

Please **_only_** suggest those widgets which you would be interested in developing.

> Note: This issue is only to get suggestions. It should not be claimed and no points will be awarded for giving suggestions in this issue.

**Comment by Vishesh-Vijay** [comment]
bookmark widget

**Comment by atharva-gadekar** [comment]
> bookmark widget

That is already under development @Vishesh-Vijay

**Comment by Kali-Decoder** [comment]
- Black - white Toggler Button on Website 
- Alarm

**Comment by abhinavs1920** [comment]
A text widget ( Containing tasks or thoughts )
