### ISSUE TITLE
Swipe left on the Home Screen to load second page

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#36]
## Instructions
- Create a new page inside the `pages` folder, named `Kanban.js`
- Swiping from right to left on the Home Page must take the user to this (Kanban) page.
- There should be a very minimal `>` at the middle right of the Home Screen. Clicking it should also bring up the Kanban Page.
- You have to make sure that there is a sliding transition between the screen change. 
- You just have to create the Kanban Page and write `This is the Kanban Page` inside it. You can leave the rest of the page blank.
- Swiping left to right on the Kanban Page must bring the user back to the Home Screen with the sliding transition.
- Make sure that the background image on the Home Screen is not reloaded after any transition.

**Comment by ananyaa07** [comment]
Claim

**Comment by atharva-gadekar** [comment]
Open For Claim

**Comment by atharva-gadekar** [comment]
Tips: You will need to detect swipes and navigate to a different page. You need to animate the page transition using Framer Motion.

**Comment by GammaMicrowave** [comment]
claim

**Comment by atharva-gadekar** [comment]
Amazing work @GammaMicrowave! Issue closed
