### ISSUE TITLE
Implement Calendar Button on Home Page

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#37]
## Instructions
- Refer to [this](https://www.figma.com/file/oSJGhiZsnyFtukferlag60/Untitled-(Copy)?node-id=0%3A1&t=ODTFXdxmtvllWWTX-0) and display the calendar button.
- On Clicking the button (which should be placed at the bottom right), the user must be redirected to any calendar-displaying website.
- Make sure the design is responsive.

### The Design 
![image](https://user-images.githubusercontent.com/97454406/209627230-ff70c2be-8ac0-4f2e-9643-66934eb049b1.png)

Later on, this calendar widget will be implemented using Ant Design. A separate issue will be put up for that task.

**Comment by Kali-Decoder** [comment]
Claim

**Comment by atharva-gadekar** [comment]
@Kali-Decoder If you are able to implement this calendar using Ant Design, it will be great too. I will consider increasing the points for this issue then.

**Comment by Kali-Decoder** [comment]
Can you tell me what should i do for increasing points in this issue

**Comment by atharva-gadekar** [comment]
You must implement the calendar within the website itself i.e without redirecting to another website. You can do this using Ant Design Calendar. Make sure that it goes well with the design.

**Comment by Kali-Decoder** [comment]
Okk i will implement please increase points

**Comment by Kali-Decoder** [comment]
@atharva-gadekar  bhaiya can you increase Points so that I raised PR for this . 
Implementing both button and calendar page .

**Comment by atharva-gadekar** [comment]
Completed by @Kali-Decoder
