### ISSUE TITLE
Implement Sidebar on the Kanban Page

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#40]
## Instructions
- Your task is to implement the left sidebar which is shown in the design
- Hovering on the `WorkWise` name and Logo must bring up an arrow pointing towards left, which when clicked, will close the sidebar, just like a hamburger menu.
- The sidebar must be open by default.
- Clicking on the Plus must bring up a modal window using Ant Design. It should take the project name as the input.
- Just display the light mode and dark mode options as shown in the design, this issue doesn't expect you to implement their functionality. Just make sure that the user is able to toggle between them by clicking on them.
- You must make a new page inside the `pages` folder and name it `Kanban.js` (If it hasn't already been created). You have to write the code inside this file.

### Designs 
![Light mode](https://user-images.githubusercontent.com/97454406/210060274-3740420f-830f-4590-bc8e-eab1dc5591b5.png)
Figma Link : [Click here](https://www.figma.com/file/nkN2oNIDLm791Wb5N7BCP2/Final-WorkWise-Designs?node-id=0%3A1&t=j9VFthzl7kEoTrz6-1)

**Comment by vishalola** [comment]
claim

**Comment by atharva-gadekar** [comment]
@vishalola  I forgot to mention this, make sure you make a component for the sidebar and use it in the Kanban.js page instead of writing the code directly inside the Kanban.js page.

**Comment by vishalola** [comment]
okay I'll keep that in mind

**Comment by Manas2403** [comment]
updates @vishalola  ?

**Comment by atharva-gadekar** [comment]
Great work! @vishalola Thankyou for completing this issue
