### ISSUE TITLE
Fix date and time bug

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#41]
## Instructions 
- The time displayed on the HomePage does not update. It only updates after refreshing the website
- The same is true for the date displayed on the HomePage.
- Your task is to fix this issue and find out the reason for this bug in the current code.

**Comment by ananyaa07** [comment]
claim

**Comment by Kali-Decoder** [comment]
Claim

**Comment by atharva-gadekar** [comment]
Good Work @ananyaa07! Bug resolved
