### ISSUE TITLE
Improve Styling of Quotes

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/WorkWise#43]
For this task, you have to improve the styling of the quotes component in `src/components/Quotes.jsx`. It should  go with the color theme of the website.

**Comment by abhinavs1920** [comment]
Claim

**Comment by Manas2403** [comment]
Assigned to @abhinavs1920

**Comment by atharva-gadekar** [comment]
@abhinavs1920 Updates?

**Comment by abhinavs1920** [comment]
Will complete today itself

**Comment by abhinavs1920** [comment]
The quote on the homepage is looking good , please tell me what I have to change

**Comment by atharva-gadekar** [comment]
@abhinavs1920 you have the liberty of deciding that. You can display it like the one shown in this image below 
![image](https://user-images.githubusercontent.com/97454406/211043893-fa823184-d1f3-4ac1-a5a5-f2da4f0035cb.png)

Complete this issue by tomorrow evening. Hopefully that is sufficient time to work on this issue.

**Comment by Manas2403** [comment]
Updates @abhinavs1920 ?
