### ISSUE TITLE
Implement Header for the Kanban Page

### ISSUE THREAD

**Issue by Manas2403** [opencodeiiita/WorkWise#44]
## Instructions
- Make a `Header` component in the `Components` folder.   

- Implement the Calendar feature as shown in the design. Display the current date. Clicking on the Date must display a minimal calendar from Ant Design.

- Display a temporary Avatar

- You will have to implement the Search feature. It should have a minimal drop-down list upon searching for a project. The list of projects will be available in the left side bar. 
(The sidebar is under development and will be available soon)

### Designs 
![Light mode](https://user-images.githubusercontent.com/97454406/210060274-3740420f-830f-4590-bc8e-eab1dc5591b5.png)
Figma Link : [Click here](https://www.figma.com/file/nkN2oNIDLm791Wb5N7BCP2/Final-WorkWise-Designs?node-id=0%3A1&t=j9VFthzl7kEoTrz6-1)

**Comment by Kali-Decoder** [comment]
claim

**Comment by Manas2403** [comment]
Assigned to @Kali-Decoder

**Comment by atharva-gadekar** [comment]
@Kali-Decoder Updates?

**Comment by Kali-Decoder** [comment]
Bhaiya partial marks deke close krdo mujhe ek dusra kaam h 🥲🥲🥲

**Comment by Kali-Decoder** [comment]
Khali search implementation left h

**Comment by atharva-gadekar** [comment]
Design changes bhi chahiye the
