### ISSUE TITLE
Implement Cards

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#46]
## Instructions
- Make a new file in the `utils` folder named `Cards.json`. In this file, make an array of Objects. The Objects should have the following keys.
  - id : (String)
  - category : (String)
  - tags : (An Array of Strings)
  - imgUrl : (String)
  - heading : (String)
  - desc : (String)
  - date : (String of format `YYYY-MM-DD`)
  - priority : (String)
  - details : (Leave as an empty String for now).
- Make multiple such objects inside the array with random data.
- Make a new component inside the `components` folder called `Card.js`. Fetch the data from the `Cards.json` file and display it using cards. Refer to the Figma design of the cards. 
- The final cards must look like the ones shown in the design. Make sure to display each field from the JSON file as shown in the design.
- If the object does not have an `imgUrl` then don't display the image at all in the card.
- The cards should be responsive to some extent.

### Card Designs
![image](https://user-images.githubusercontent.com/97454406/210352937-2ea61c6e-0e5e-4b8e-9819-7eee496a7d37.png)
 
![image](https://user-images.githubusercontent.com/97454406/210352983-f3157417-dc27-4b2e-bec0-ea4e9d92f8c4.png)

Figma Design Link : [Click Here](https://www.figma.com/file/nkN2oNIDLm791Wb5N7BCP2/Final-WorkWise-Designs?node-id=0%3A1&t=j9VFthzl7kEoTrz6-1)

**Comment by aasthaaaa7** [comment]
claim

**Comment by atharva-gadekar** [comment]
@aasthaaaa7 Updates?

**Comment by aasthaaaa7** [comment]
im working on it

**Comment by atharva-gadekar** [comment]
Issue open for reassignment

**Comment by SanyamAgrawal07** [comment]
claim

**Comment by GammaMicrowave** [comment]
Claim

**Comment by atharva-gadekar** [comment]
Great Work @SanyamAgrawal07! Issue closed
