### ISSUE TITLE
Install Tailwind in this project

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#5]
## Steps to solve this issue successfully:
- Clone this project in your local system
- Install tailwind following the documentation given on its website: https://tailwindcss.com/docs/guides/create-react-app
- Change the content on the homepage
- Submit a PR
- Note : The PR must be submitted within 2 days

Please don't create another react project, just install tailwind, following the documentation.

If you need any help regarding this issue, you can ping me on Discord on the workwise help channel. My Discord Username is @Dreaming_Doer

**Comment by ananyaa07** [comment]
claim

**Comment by atharva-gadekar** [comment]
This issue has been completed
