### ISSUE TITLE
Implement Nested Routing

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#50]
## Instructions
- Your task is to make different routes and redirect the user to that specific route when the user clicks on the project in the Sidebar.
- For eg. consider this Sidebar Project List
  - OpenCode
  - Lost and Found
  - WorkWise
  - Academics
- Let's say the user clicks on `Lost and Found` in the side bar. The user should then be redirected to this path: `/kanban/lostandfound`. 
- This path must render the name of the project, the sidebar, and the heading bar. As the heading bar is still under development, just place a white div to represent it.
- This is how your page should look like after the redirect : 
![image](https://user-images.githubusercontent.com/97454406/211049656-d8b0c6ac-fa75-4f7d-900c-5de98a16e9f2.png)
- Take into consideration that the routes must be dynamic i.e the Project Names would be different for different users.

Desgin File link : [Here](https://www.figma.com/file/nkN2oNIDLm791Wb5N7BCP2/Final-WorkWise-Designs?node-id=1%3A601&t=lbCK2AsXn0It3FsF-1)

**Comment by GammaMicrowave** [comment]
Claim
