### ISSUE TITLE
Add Columns

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#52]
## Instructions
1. Your task is to implement 4 initial columns. You can view the design below for a better understanding.
![image](https://user-images.githubusercontent.com/97454406/211724479-9f5b025f-3d0d-4f97-8f82-4fbdef1c4d37.png)

2. Clicking on the plus icon, must bring up a modal window, which will ask the user to enter the details of the card. 
3. You can use the Modal Window from Ant Design.  The modal window must as for the card title, description, date, priority, tags and image url. You may use Ant design for this. 
4. You must use this data to display the card in the selected column. You must use the card component for this purpose. The new added card must be lower to all previously added cards i.e it must be appended to end of the column. 
5. You have to store all this card data in the local storage.
6. There should also be a 5th column, clicking on which will add a new column. 
![image](https://user-images.githubusercontent.com/97454406/211725000-503e505b-b561-492c-9baf-a3946a9c3fc0.png)

Design Link : https://www.figma.com/file/nkN2oNIDLm791Wb5N7BCP2/Final-WorkWise-Designs?node-id=0%3A1&t=GKqzaj1T1L7lZi4p-1

**Comment by Koshal7** [comment]
Claim

**Comment by atharva-gadekar** [comment]
You have 2 days to complete this issue. All the best

**Comment by atharva-gadekar** [comment]
@Koshal7 Updates?

**Comment by atharva-gadekar** [comment]
@Koshal7 Updates?

**Comment by Koshal7** [comment]
I was travelling to college so couldn't complete it.

**Comment by SanyamAgrawal07** [comment]
Claim
