### ISSUE TITLE
Implement Card Drag and Drop 

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#53]
## Instructions
1. Study the [react-beautiful-dnd](https://www.npmjs.com/package/react-beautiful-dnd). 
2. Look at this gif given below.
![](https://user-images.githubusercontent.com/2182637/53614150-efbed780-3c2c-11e9-9204-a5d2e746faca.gif)
3. You have to replicate this gif. You must make 4 different columns and implement the drag-and-drop feature as shown in the gif.
4. You must use the cards from the `/cards` route.

**Comment by GammaMicrowave** [comment]
Claim

**Comment by atharva-gadekar** [comment]
Great work @GammaMicrowave !
