### ISSUE TITLE
Add a Loader for Homepage

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#58]
## Instructions
1. You are supposed to display a loader when the user opens the website. 
2. The loader must be displayed until the background image has been completely loaded.
3. The loader must look like the one shown in [this](https://www.figma.com/proto/hv8hIEn0DrE8Ok4YGXhf0B/WorkWise-Loader?node-id=1%3A30&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A30) animation. Note, the animation is low quality therefore you must not use the gif shown in the animation. You must animate the WorkWise logo yourself using some basic CSS for rotation and size scaling.
4. You can find the WorkWise logo [here](https://www.figma.com/file/gtCWLq9mxxM3b8r9gkbxti/WorkWise-logo-(Copy)?node-id=0%3A1&t=0dcz9maaIevOYMRR-1).

> PS: The deadline for this issue is tonight. You must submit a PR for this before 12 am today. This is one of the last issues for WorkWise.

**Comment by atharva-gadekar** [comment]
Points increased to 50 as there were no claims

**Comment by vishalola** [comment]
claim

**Comment by atharva-gadekar** [comment]
Thanks @vishalola
