### ISSUE TITLE
Delete Project and Project Title Styling

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#59]
## Instructions
1. Currently, if a particular project has been selected, there is a box around it. 
    1. Your task is to display a delete icon beside this box, when the user hovers over the selected project title in the Sidebar. 
    2. Make sure that the delete icon is only displayed beside the **selected** project's box when the user hovers over it. 
    3. Upon clicking the delete icon, the project must be deleted from the sidebar or must no longer be seen in the sidebar.
2. Currently, this is what the project title looks like
![image](https://user-images.githubusercontent.com/97454406/212570248-3ca788e7-1dca-476e-b22b-5344f9a755b6.png)
    1. Your task is to style it like what is shown in the design. You can find the design [here](https://www.figma.com/file/nkN2oNIDLm791Wb5N7BCP2/Final-WorkWise-Designs?node-id=1%3A601&t=FXexzZ7VJkNaHnk9-1). This is how it should look after the styling changes 
![image](https://user-images.githubusercontent.com/97454406/212570224-c085b2f9-e750-4c95-9dd6-08827893a929.png)

> PS:  You must submit a PR for this issue before 11:59pm tonight.

**Comment by SanyamAgrawal07** [comment]
Claim
