### ISSUE TITLE
Design Home Page (Front Page) for WorkWise

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#6]
## Things to consider before making a design :
- The page should have a background image.
- The page will have several widgets like Time, Date, Weather, Motivational Quote, Focus Timer, Bookmarks, Settings etc.
- You take references from your Windows Lockscreen or from a  browser extension named [Momentum](https://chrome.google.com/webstore/detail/momentum/laookkfknpbbblfpciffpaejjkokdgca)
- The Home page should not look cluttered. Try to make its design minimal
- If you wish, you can make separate designs for Light Theme and Dark Theme. Figma Files having both the themes will have an higher chance of getting merged.

### Submission Guidelines :
- Add your Figma link in the `design.json` file in the workwise folder.
- Make sure the visibility of the Figma File is public.
- Note that the issue is **_Open for All_**. There is no need to claim this issue. You can directly submit a PR

**Comment by atharva-gadekar** [comment]
![image](https://user-images.githubusercontent.com/97454406/208352834-ef7eac96-a534-4d11-9e25-4da7bcd478f4.png)
Reference image for design. You can take inspiration from this design.

**Comment by Kali-Decoder** [comment]
claim

**Comment by atharva-gadekar** [comment]
Hello @Kali-Decoder, we will be proceeding through this project by giving out multiple issues. There will be multiple widgets
whose issues will also be released gradually.
This issue is only for Design. There is no need to claim this issue, you can directly submit a PR for this in the `designs.json` file.
Stay tuned for more issues.

As far as other issues are concerned, they will only be assigned to the ones who comment claim the first.

**Comment by atharva-gadekar** [comment]
You can Google "Best Rainmeter Skins" to get a reference for this design. You can make any design you like. However, make sure that the design chosen will go with all nature backgrounds i.e, the design chosen should not be wallpaper specific.
