### ISSUE TITLE
Last Issue for WorkWise :(

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#61]
> I hope you guys got to learn a lot from my project idea. It was a great experience for me to be a mentor for this project. We now have a decently functioning website. And I believe, with this last issue, we will have a fully working **_Version 1.0_** of WorkWise. I am thankful to you all for all the amazing work that you guys did.

## Last Instructions
 - Clicking on the plus button must add a card in that particular column
 - This must be done by adding the form details into an array. The array has already been stored in local storage.
 - There is a bug which leads to a null route upon creating a new project for the first time. This bug must be fixed.

**Comment by GammaMicrowave** [comment]
Claim

**Comment by atharva-gadekar** [comment]
Thanks. Great work!
