### ISSUE TITLE
Fetch Random Background Image

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#8]
## Instructions
- You have to clear the text on the home screen and add a background image to it, which will cover the entire display.
- Make sure that the image is non-scrollable in the x and y axes.
- The background image must be random and must be fetched using an API. You can use the [Unsplash API](https://unsplash.com/developers) for this work. 
- Make a `pages` folder in the `src` folder. Then, create a `homepage.js` file in it and set its background using the API.
- Ping me on Discord to get the API key. You can ping me or Manas or Anurag if you have any other doubts as well.

**Comment by ananyaa07** [comment]
claim

**Comment by GammaMicrowave** [comment]
Claim

**Comment by atharva-gadekar** [comment]
@GammaMicrowave More issues will be coming up. Stay tuned!

**Comment by atharva-gadekar** [comment]
@ananyaa07  You have a time of two days to complete this issue. Please submit the PR before the deadline. If you need any help, you can reach out to us. Also, in case you submit a PR after the Fetch Time issue is closed, make sure that your code has no merge conflicts with this repo. Make sure to fetch upstream your forked repo before submitting a PR.
