### ISSUE TITLE
Fetch Current Time using location-based API

### ISSUE THREAD

**Issue by atharva-gadekar** [opencodeiiita/WorkWise#9]
## Instructions
- Fetch the current time (using location-based API) and display it in the middle of the homepage. Hardcode the location.
- Make sure that the text is large enough.
- The time has to be displayed primarily in a digital format, not an analogue format.
- You can add a carousel to switch between digital and analogue formats
- Make a new folder called `components` inside the `src` folder. Inside the `components` folder make a file called `time.js` and write the code for this component inside it.
- Call this component on the `homepage.js` file. 
- If you need any help, you can ping me, Manas or Anurag on Discord.

**Comment by Shubhankit-Pandey** [comment]
claim

**Comment by atharva-gadekar** [comment]
> claim

You have a time of two days to complete this issue. Please submit the PR before the deadline. If you need any help, you can reach out to us. Also, in case you submit a PR after the Background Image issue is closed, make sure that your code has no merge conflicts with this repo. Make sure to fetch upstream your forked repo before submitting a PR.

**Comment by gauravsahu21** [comment]
Hey, can I work on this issue?

**Comment by Manas2403** [comment]
Sorry, the issue has already been claimed.

**Comment by atharva-gadekar** [comment]
@Shubhankit-Pandey Updates?

**Comment by Shubhankit-Pandey** [comment]
The work is still under process but it will be done before the deadline.

**Comment by Kali-Decoder** [comment]
claim

**Comment by Kali-Decoder** [comment]
claim
